# -*- coding: utf-8 -*-
"""Interactive Errors+ Files

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115jPD1FXXoPmHQ2FqpWfAiQ8lsiMnHI8

# Files

Python uses file objects to interact with external files on your computer. These file objects can be any sort of file you have on your computer, whether it be an audio file, a text file, emails, Excel documents, etc. Note: You will probably need to install certain libraries or modules to interact with those various file types, but they are easily available


Python has a built-in open function that allows us to open and play with basic file types. First we will need a file though. We're going to use some IPython magic to create a text file!

## IPython Writing a File 
#### This function is specific to jupyter notebooks! Alternatively, quickly create a simple .txt file with sublime text editor.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test.txt
# Hello, this is a quick test file.

"""## Python Opening a file

Let's being by opening the file test.txt that is located in the same directory as this notebook. For now we will work with files located in the same directory as the notebook or .py script you are using.

It is very easy to get an error on this step:
"""

myfile = open('whoops.txt')

"""To avoid this error,make sure your .txt file is saved in the same location as your notebook, to check your notebook location, use **pwd**:"""

pwd

"""**Alternatively, to grab files from any location on your computer, simply pass in the entire file path. **

For Windows you need to use double \ so python doesn't treat the second \ as an escape character, a file path is in the form:

    myfile = open("C:\\Users\\YourUserName\\Home\\Folder\\myfile.txt")

For MacOS and Linux you use slashes in the opposite direction:

    myfile = open("/Users/YouUserName/Folder/myfile.txt")
"""

# Open the text.txt we made earlier
my_file = open('test.txt')

# We can now read the file
my_file.read()

# But what happens if we try to read it again?
my_file.read()

"""This happens because you can imagine the reading "cursor" is at the end of the file after having read it. So there is nothing left to read. We can reset the "cursor" like this:"""

# Seek to the start of file (index 0)
my_file.seek(0)

# Now read again
my_file.read()

"""You can read a file line by line using the readlines method. Use caution with large files, since everything will be held in memory. We will learn how to iterate over large files later in the course."""

# Readlines returns a list of the lines in the file
my_file.seek(0)
my_file.readlines()

"""When you have finished using a file, it is always good practice to close it."""

my_file.close()

"""## Writing to a File

By default, the `open()` function will only allow us to read the file. We need to pass the argument `'w'` to write over the file. For example:
"""

# Add a second argument to the function, 'w' which stands for write.
# Passing 'w+' lets us read and write to the file

my_file = open('test.txt','w+')

"""### <strong><font color='red'>Use caution!</font></strong> 
Opening a file with `'w'` or `'w+'` truncates the original, meaning that anything that was in the original file **is deleted**!
"""

# Write to the file
my_file.write('This is a new line')

# Read the file
my_file.seek(0)
my_file.read()

my_file.close()  # always do this when you're done with a file

"""## Appending to a File
Passing the argument `'a'` opens the file and puts the pointer at the end, so anything written is appended. Like `'w+'`, `'a+'` lets us read and write to a file. If the file does not exist, one will be created.
"""

my_file = open('test.txt','a+')
my_file.write('\nThis is text being appended to test.txt')
my_file.write('\nAnd another line here.')

my_file.seek(0)
print(my_file.read())

my_file.close()

"""### Appending with `%%writefile`
We can do the same thing using IPython cell magic:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a test.txt
# 
# This is text being appended to test.txt
# And another line here.

"""Add a blank space if you want the first line to begin on its own line, as Jupyter won't recognize escape sequences like `\n`

## Iterating through a File

Lets get a quick preview of a for loop by iterating over a text file. First let's make a new text file with some IPython Magic:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test.txt
# First Line
# Second Line

"""Now we can use a little bit of flow to tell the program to for through every line of the file and do something:"""

for line in open('test.txt'):
    print(line)

"""Don't worry about fully understanding this yet, for loops are coming up soon. But we'll break down what we did above. We said that for every line in this text file, go ahead and print that line. It's important to note a few things here:

1. We could have called the "line" object anything (see example below).
2. By not calling `.read()` on the file, the whole text file was not stored in memory.
3. Notice the indent on the second line for print. This whitespace is required in Python.
"""

# Pertaining to the first point above
for asdf in open('test.txt'):
    print(asdf)

"""We'll learn a lot more about this later, but up next: Sets and Booleans!"""



"""# Errors and Exception Handling"""

print('Hello)

"""Note how we get a SyntaxError, with the further description that it was an EOL (End of Line Error) while scanning the string literal. This is specific enough for us to see that we forgot a single quote at the end of the line. Understanding these various error types will help you debug your code much faster. 

This type of error and description is known as an Exception. Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal.

## try and except

The basic terminology and syntax used to handle errors in Python are the <code>try</code> and <code>except</code> statements. The code which can cause an exception to occur is put in the <code>try</code> block and the handling of the exception is then implemented in the <code>except</code> block of code. The syntax follows:

    try:
       You do your operations here...
       ...
    except ExceptionI:
       If there is ExceptionI, then execute this block.
    except ExceptionII:
       If there is ExceptionII, then execute this block.
       ...
    else:
       If there is no exception then execute this block. 

We can also just check for any exception with just using <code>except:</code> To get a better understanding of all this let's check out an example: We will look at some code that opens and writes a file:
"""

try:
    f = open('testfile','w')
    f.write('Test write this')
except IOError:
    # This will only check for an IOError exception and then execute this print statement
    print("Error: Could not find file or read data")
else:
    print("Content written successfully")
    f.close()

"""Now let's see what would happen if we did not have write permission (opening only with 'r'):"""

try:
    f = open('testfile','r')
    f.write('Test write this')
except IOError:
    # This will only check for an IOError exception and then execute this print statement
    print("Error: Could not find file or read data")
else:
    print("Content written successfully")
    f.close()

"""Great! Notice how we only printed a statement! The code still ran and we were able to continue doing actions and running code blocks. This is extremely useful when you have to account for possible input errors in your code. You can be prepared for the error and keep running code, instead of your code just breaking as we saw above.

We could have also just said <code>except:</code> if we weren't sure what exception would occur. For example:
"""

try:
    f = open('testfile','r')
    f.write('Test write this')
except:
    # This will check for any exception and then execute this print statement
    print("Error: Could not find file or read data")
else:
    print("Content written successfully")
    f.close()

"""Great! Now we don't actually need to memorize that list of exception types! Now what if we kept wanting to run code after the exception occurred? This is where <code>finally</code> comes in.
## finally
The <code>finally:</code> block of code will always be run regardless if there was an exception in the <code>try</code> code block. The syntax is:

    try:
       Code block here
       ...
       Due to any exception, this code may be skipped!
    finally:
       This code block would always be executed.

For example:
"""

try:
    f = open("testfile", "w")
    f.write("Test write statement")
    f.close()
finally:
    print("Always execute finally code blocks")

"""We can use this in conjunction with <code>except</code>. Let's see a new example that will take into account a user providing the wrong input:"""

def askint():
    try:
        val = int(input("Please enter an integer: "))
    except:
        print("Looks like you did not enter an integer!")

    finally:
        print("Finally, I executed!")
    print(val)

askint()

askint()

"""Notice how we got an error when trying to print val (because it was never properly assigned). Let's remedy this by asking the user and checking to make sure the input type is an integer:"""

def askint():
    try:
        val = int(input("Please enter an integer: "))
    except:
        print("Looks like you did not enter an integer!")
        val = int(input("Try again-Please enter an integer: "))
    finally:
        print("Finally, I executed!")
    print(val)

askint()

"""Hmmm...that only did one check. How can we continually keep checking? We can use a while loop!"""

def askint():
    while True:
        try:
            val = int(input("Please enter an integer: "))
        except:
            print("Looks like you did not enter an integer!")
            continue
        else:
            print("Yep that's an integer!")
            break
        finally:
            print("Finally, I executed!")
        print(val)

askint()

"""So why did our function print "Finally, I executed!" after each trial, yet it never printed `val` itself? This is because with a try/except/finally clause, any <code>continue</code> or <code>break</code> statements are reserved until *after* the try clause is completed. This means that even though a successful input of **3** brought us to the <code>else:</code> block, and a <code>break</code> statement was thrown, the try clause continued through to <code>finally:</code> before breaking out of the while loop. And since <code>print(val)</code> was outside the try clause, the <code>break</code> statement prevented it from running.

Let's make one final adjustment:
"""

def askint():
    while True:
        try:
            val = int(input("Please enter an integer: "))
        except:
            print("Looks like you did not enter an integer!")
            continue
        else:
            print("Yep that's an integer!")
            print(val)
            break
        finally:
            print("Finally, I executed!")

while 1 :
  try: 
    d= int(input(' please insert an integer number '))
    v=d-5
    break 
 
  except:
    print(' L22222  ')
    continue
  else:
    print ('  3ash ')
     
  finally:
    print(' Iam in the finally ')
    print('Restart  the system ')

print(v)

askint()

while(1):
    try:
      v=int(input('please Enter a number :'))
      print(v)
    except :
      print('you have entered a string ')

askint()

"""**Great! Now you know how to handle errors and exceptions in Python with the try, except, else, and finally notation!**

# Errors and Exceptions Challenge

### Problem 1
Handle the exception thrown by the code below by using <code>try</code> and <code>except</code> blocks.
"""

for i in ['a','b','c']:
    print(i**2)

"""### Problem 2
Handle the exception thrown by the code below by using <code>try</code> and <code>except</code> blocks. Then use a <code>finally</code> block to print 'All Done.'
"""

x = 5
y = 0

z = x/y

"""### Problem 3
Write a function that asks for an integer and prints the square of it. Use a <code>while</code> loop with a <code>try</code>, <code>except</code>, <code>else</code> block to account for incorrect inputs.
"""

def ask():
    pass

ask()